import { Questionnaire, ALL_RAS_CAPABILITIES } from "@/lib/types"

export const academiaQuestionnaire: Questionnaire = {
  id: "academia",
  title: "Academia Instrument",
  description: "24 questions for universities, research institutions, and technical institutes",
  sections: [
    {
      id: "A",
      title: "Section A: Institutional Profile",
      description: "Establish your institution's profile, programme details, and pipeline",
      questionIds: ["ACAD_A_01", "ACAD_A_02", "ACAD_A_02b", "ACAD_A_03", "ACAD_A_04", "ACAD_A_05"],
    },
    {
      id: "B",
      title: "Section B: Research Capabilities",
      description: "Research capability and equipment depth",
      questionIds: ["ACAD_B_05", "ACAD_B_06", "ACAD_B_07", "ACAD_B_08", "ACAD_B_09"],
    },
    {
      id: "C",
      title: "Section C: Industry Linkage",
      description: "Test industry connections and outcomes",
      questionIds: ["ACAD_C_10", "ACAD_C_11", "ACAD_C_12"],
    },
    {
      id: "D",
      title: "Section D: Pivot Questions",
      description: "Diagnostic questions on constraints and latent capabilities",
      questionIds: ["ACAD_D_13", "ACAD_D_14"],
    },
    {
      id: "E",
      title: "Section E: Translation, Bridge Conditions, Commitment",
      description: "Translation cost and CoE commitment testing",
      questionIds: [
        "ACAD_E_15",
        "ACAD_E_16",
        "ACAD_E_17",
        "ACAD_E_18",
        "ACAD_E_19",
        "ACAD_E_20",
        "ACAD_E_21",
        "ACAD_E_22",
      ],
    },
  ],
  questions: {
    // Section A - Institutional Profile
    ACAD_A_01: {
      id: "ACAD_A_01",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "What is your institution type?",
      type: "select",
      required: true,
      options: [
        { value: "public_university", label: "Public University" },
        { value: "private_university", label: "Private University" },
        { value: "ncra_lab", label: "NCRA Lab" },
        { value: "technical_institute", label: "Technical Institute" },
        { value: "research_council", label: "Research Council" },
      ],
    },
    ACAD_A_02: {
      id: "ACAD_A_02",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "What is your RAS-relevant enrolment by degree level (current academic year)?",
      description: "Provide counts and 3-year trend for each level",
      type: "multi-row",
      maxRows: 4,
      rowFields: [
        {
          key: "degree_level",
          label: "Degree Level",
          type: "select",
          options: [
            { value: "bachelor", label: "Bachelor (BS/BE/BSc)" },
            { value: "master", label: "Master (MS/MEng/MSc)" },
            { value: "mphil", label: "MPhil" },
            { value: "phd", label: "PhD" },
          ],
        },
        { key: "enrolment", label: "Current Enrolment", type: "number" },
        {
          key: "trend",
          label: "3-Year Trend",
          type: "select",
          options: [
            { value: "strongly_declining", label: "Strongly Declining" },
            { value: "declining", label: "Declining" },
            { value: "stable", label: "Stable" },
            { value: "growing", label: "Growing" },
            { value: "strongly_growing", label: "Strongly Growing" },
          ],
        },
      ],
    },
    ACAD_A_02b: {
      id: "ACAD_A_02b",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "List your RAS-related degree programmes (up to 10)",
      type: "multi-row",
      maxRows: 10,
      rowFields: [
        { key: "programme_name", label: "Programme Name", type: "text", placeholder: "e.g., Robotics & Intelligent Systems" },
        {
          key: "level",
          label: "Level",
          type: "select",
          options: [
            { value: "bs", label: "BS" },
            { value: "be", label: "BE" },
            { value: "bsc", label: "BSc" },
            { value: "ms", label: "MS" },
            { value: "meng", label: "MEng" },
            { value: "msc", label: "MSc" },
            { value: "mphil", label: "MPhil" },
            { value: "phd", label: "PhD" },
            { value: "diploma", label: "Diploma" },
            { value: "certificate", label: "Certificate" },
          ],
        },
        { key: "year_established", label: "Year Established", type: "number" },
        { key: "current_enrolment", label: "Current Enrolment", type: "number" },
      ],
    },
    ACAD_A_03: {
      id: "ACAD_A_03",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "How many full-time PhD faculty are active in RAS research?",
      type: "number",
      required: true,
    },
    ACAD_A_04: {
      id: "ACAD_A_04",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "What are your last cohort graduate destinations by degree level?",
      description: "Provide percentage split for each degree level (must sum to 100%)",
      type: "multi-row",
      maxRows: 3,
      rowFields: [
        {
          key: "degree_level",
          label: "Degree Level",
          type: "select",
          options: [
            { value: "bachelor", label: "Bachelor" },
            { value: "master", label: "Master" },
            { value: "phd", label: "PhD" },
          ],
        },
        { key: "domestic_industry", label: "Domestic Industry (%)", type: "number" },
        { key: "domestic_public", label: "Domestic Public Sector (%)", type: "number" },
        { key: "further_study_pk", label: "Further Study Pakistan (%)", type: "number" },
        { key: "further_study_abroad", label: "Further Study Abroad (%)", type: "number" },
        { key: "employed_abroad", label: "Employed Abroad (%)", type: "number" },
        { key: "unemployed", label: "Unemployed (%)", type: "number" },
      ],
    },
    ACAD_A_05: {
      id: "ACAD_A_05",
      section: "A",
      sectionTitle: "Institutional Profile",
      question: "What is your faculty composition by qualification?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "phds_supervising", label: "PhDs Supervising RAS Research" },
        { key: "ms_teaching", label: "MS-qualified Teaching Staff" },
        { key: "industry_experienced", label: "Industry-experienced Faculty (3+ years)" },
        { key: "visiting_adjunct", label: "Visiting/Adjunct Industry Experts" },
      ],
    },

    // Section B - Research Capabilities
    ACAD_B_05: {
      id: "ACAD_B_05",
      section: "B",
      sectionTitle: "Research Capabilities",
      question: "Describe your top 3 RAS research lines",
      type: "multi-row",
      maxRows: 3,
      rowFields: [
        { key: "method", label: "Method/Approach", type: "text", placeholder: "Max 280 characters" },
        { key: "problem_solved", label: "Problem Solved", type: "text" },
        {
          key: "trl",
          label: "Current TRL",
          type: "select",
          options: [
            { value: "1", label: "TRL 1 - Basic Principles" },
            { value: "2", label: "TRL 2 - Technology Concept" },
            { value: "3", label: "TRL 3 - Proof of Concept" },
            { value: "4", label: "TRL 4 - Lab Validation" },
            { value: "5", label: "TRL 5 - Relevant Environment" },
            { value: "6", label: "TRL 6 - Demonstrated" },
            { value: "7", label: "TRL 7 - Operational" },
            { value: "8", label: "TRL 8 - Qualified" },
            { value: "9", label: "TRL 9 - Mission Proven" },
          ],
        },
      ],
    },
    ACAD_B_06: {
      id: "ACAD_B_06",
      section: "B",
      sectionTitle: "Research Capabilities",
      question: "Rate your research strength (1-5) across 24 RAS capabilities",
      description: "1 = No capability, 5 = World-class capability",
      type: "likert-matrix",
      required: true,
      items: ALL_RAS_CAPABILITIES,
    },
    ACAD_B_07: {
      id: "ACAD_B_07",
      section: "B",
      sectionTitle: "Research Capabilities",
      question: "What industrial-grade RAS hardware do you have operational?",
      type: "multi-number",
      required: false,
      numberFields: [
        { key: "six_axis_arms", label: "6-axis Arms" },
        { key: "cobots", label: "Cobots" },
        { key: "agv_amr", label: "AGVs/AMRs" },
        { key: "uav_platforms", label: "UAV Platforms" },
        { key: "ugvs", label: "UGVs" },
        { key: "gpu_clusters", label: "GPU Clusters" },
        { key: "other", label: "Other" },
      ],
    },
    ACAD_B_08: {
      id: "ACAD_B_08",
      section: "B",
      sectionTitle: "Research Capabilities",
      question: "How many hands-on robotics hours per student per semester?",
      type: "number",
      required: true,
    },
    ACAD_B_09: {
      id: "ACAD_B_09",
      section: "B",
      sectionTitle: "Research Capabilities",
      question: "What are your IP outputs in the last 5 years?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "patents_filed", label: "Patents Filed" },
        { key: "patents_granted", label: "Patents Granted" },
        { key: "spin_outs", label: "Spin-outs" },
      ],
    },

    // Section C - Industry Linkage
    ACAD_C_10: {
      id: "ACAD_C_10",
      section: "C",
      sectionTitle: "Industry Linkage",
      question: "Name your top 3 Pakistani firm engagements in last 3 years with outcomes",
      type: "multi-row",
      maxRows: 3,
      rowFields: [
        { key: "firm_name", label: "Firm Name", type: "text" },
        { key: "outcome", label: "Outcome Description", type: "text", placeholder: "Max 280 characters" },
      ],
    },
    ACAD_C_11: {
      id: "ACAD_C_11",
      section: "C",
      sectionTitle: "Industry Linkage",
      question: "What is the total value of industry-sponsored RAS contracts in last 36 months?",
      type: "composite",
      required: true,
      compositeFields: [
        { key: "total_pkr", label: "Total PKR (millions)", type: "number", required: true },
        {
          key: "sectors",
          label: "Sectors",
          type: "multi-select",
          options: [
            { value: "textiles", label: "Textiles" },
            { value: "automotive", label: "Automotive" },
            { value: "pharma", label: "Pharma" },
            { value: "food_beverage", label: "Food & Beverage" },
            { value: "surgical", label: "Surgical" },
            { value: "logistics", label: "Logistics" },
            { value: "agri", label: "Agriculture" },
            { value: "cement_steel", label: "Cement/Steel" },
            { value: "chemicals", label: "Chemicals" },
            { value: "electronics", label: "Electronics" },
            { value: "defence", label: "Defence" },
            { value: "other", label: "Other" },
          ],
        },
      ],
    },
    ACAD_C_12: {
      id: "ACAD_C_12",
      section: "C",
      sectionTitle: "Industry Linkage",
      question: "What is the single biggest barrier to commercialising your strongest research line?",
      description: "Provide specific failure point with named example",
      type: "text",
      maxChars: 280,
      required: true,
    },

    // Section D - Pivot Questions
    ACAD_D_13: {
      id: "ACAD_D_13",
      section: "D",
      sectionTitle: "Pivot Questions",
      question: "What are the top 3 constraints preventing research-to-industry translation?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "no_industry_partner", label: "No Industry Partner" },
        { value: "no_seed_capital", label: "No Seed Capital" },
        { value: "equipment_gap", label: "Equipment Gap" },
        { value: "talent_drain", label: "Talent Drain" },
        { value: "ip_policy_unclear", label: "IP Policy Unclear" },
        { value: "incentives_misaligned", label: "Incentives Misaligned" },
        { value: "admin_burden", label: "Administrative Burden" },
        { value: "export_red_tape", label: "Export Red Tape" },
        { value: "no_validation_route", label: "No Validation Route" },
        { value: "other", label: "Other" },
      ],
    },
    ACAD_D_14: {
      id: "ACAD_D_14",
      section: "D",
      sectionTitle: "Pivot Questions",
      question: "What research capability/dataset/technique has industrial value but lacks a partner?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      prascOptIn: true,
      options: [
        { value: "curated_dataset", label: "Curated Dataset" },
        { value: "simulation_environment", label: "Simulation Environment" },
        { value: "niche_algorithm", label: "Niche Algorithm" },
        { value: "tested_prototype", label: "Tested Prototype" },
        { value: "certified_lab", label: "Certified Lab" },
        { value: "trained_cohort", label: "Trained Cohort" },
        { value: "partner_network", label: "Partner Network" },
        { value: "domain_expertise", label: "Domain Expertise" },
        { value: "other", label: "Other" },
      ],
    },

    // Section E - Translation, Bridge Conditions, Commitment
    ACAD_E_15: {
      id: "ACAD_E_15",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "What resources are needed to reach export-ready product for your top 3 research lines?",
      type: "multi-row",
      maxRows: 3,
      rowFields: [
        { key: "research_line", label: "Research Line", type: "text" },
        { key: "pkr_million", label: "PKR Million", type: "number" },
        { key: "months", label: "Months", type: "number" },
        { key: "fte_engineers", label: "FTE Engineers", type: "number" },
      ],
    },
    ACAD_E_16: {
      id: "ACAD_E_16",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "Rank top 2 most decisive external inputs for translation",
      type: "rank",
      rankCount: 2,
      required: true,
      options: [
        { value: "industry_pilot_funding", label: "Industry Pilot Funding" },
        { value: "equipment_grant", label: "Equipment Grant" },
        { value: "ip_policy_reform", label: "IP Policy Reform" },
        { value: "industrial_phd_programme", label: "Industrial PhD Programme" },
        { value: "technology_transfer_office", label: "Technology Transfer Office" },
        { value: "export_certification", label: "Export Certification" },
        { value: "investor_introduction", label: "Investor Introduction" },
        { value: "matched_grant", label: "Matched Grant" },
      ],
    },
    ACAD_E_17: {
      id: "ACAD_E_17",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "Rate your curriculum depth (1-5) across 9 RAS-critical topics",
      description: "1 = Not covered, 5 = Industry-ready depth",
      type: "likert-matrix",
      required: true,
      items: [
        { id: "control_systems", label: "Control Systems" },
        { id: "ros2", label: "ROS2" },
        { id: "computer_vision", label: "Computer Vision" },
        { id: "machine_learning", label: "Machine Learning" },
        { id: "embedded_systems", label: "Embedded Systems" },
        { id: "mechatronics", label: "Mechatronics" },
        { id: "industrial_automation", label: "Industrial Automation" },
        { id: "system_safety", label: "System Safety" },
        { id: "ai_ethics", label: "AI Ethics" },
      ],
    },
    ACAD_E_18: {
      id: "ACAD_E_18",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "What is the status of industrial practicum (6-week mandatory)?",
      type: "select",
      required: true,
      options: [
        { value: "mandatory", label: "Mandatory" },
        { value: "optional", label: "Optional" },
        { value: "none", label: "None" },
        { value: "planned", label: "Planned" },
      ],
    },
    ACAD_E_19: {
      id: "ACAD_E_19",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "Which OEM training partnerships do you have?",
      type: "multi-select",
      required: false,
      options: [
        { value: "abb", label: "ABB" },
        { value: "fanuc", label: "FANUC" },
        { value: "kuka", label: "KUKA" },
        { value: "universal_robots", label: "Universal Robots" },
        { value: "siemens", label: "Siemens" },
        { value: "nvidia", label: "NVIDIA" },
        { value: "festo", label: "Festo" },
        { value: "mitsubishi", label: "Mitsubishi" },
        { value: "rockwell", label: "Rockwell" },
        { value: "other", label: "Other" },
      ],
    },
    ACAD_E_20: {
      id: "ACAD_E_20",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "What outcomes can you deliver with PRASC funding (200m one-time + 50m/yr x 5)?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "enrolment_uplift_pct", label: "Enrolment Uplift (%)" },
        { key: "new_labs", label: "New Labs" },
        { key: "patents_5y", label: "Patents (5 years)" },
        { key: "spin_outs_5y", label: "Spin-outs (5 years)" },
        { key: "industry_projects_5y", label: "Industry Projects (5 years)" },
      ],
    },
    ACAD_E_21: {
      id: "ACAD_E_21",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "How willing are you to sign a Centre of Excellence agreement with binding KPIs?",
      description: "1 = Strongly reject, 5 = Ready to sign within 90 days",
      type: "likert",
      required: true,
    },
    ACAD_E_22: {
      id: "ACAD_E_22",
      section: "E",
      sectionTitle: "Translation & Commitment",
      question: "What is the single most consequential change PRASC could make?",
      description: "Provide named entity or example (max 280 characters)",
      type: "text",
      maxChars: 280,
      required: true,
    },
  },
}
