import { Questionnaire } from "@/lib/types"

export const governmentQuestionnaire: Questionnaire = {
  id: "government",
  title: "Government Instrument",
  description: "17 questions for federal and provincial ministries, regulators, and SOEs",
  sections: [
      {
      id: "0",
      title: "Section 0: Personal Information",
      description: "  Collect respondent's contact details for follow-up and validation purposes",
      questionIds: ["GOV_0_01", "GOV_0_02", "GOV_0_03", "GOV_0_04"],
    },
    {
      id: "A",
      title: "Section A: Organisation and Mandate",
      description: "Identify the organisation's mandate and budget",
      questionIds: ["GOV_A_01", "GOV_A_02", "GOV_A_03"],
    },
    {
      id: "B",
      title: "Section B: Current RAS Activity",
      description: "Capture current RAS activity and programmes",
      questionIds: ["GOV_B_04", "GOV_B_05", "GOV_B_06", "GOV_B_07", "GOV_B_08"],
    },
    {
      id: "C",
      title: "Section C: Regulatory Posture",
      description: "Score regulatory readiness across key areas",
      questionIds: ["GOV_C_09", "GOV_C_10", "GOV_C_11"],
    },
    {
      id: "D",
      title: "Section D: Pivot Questions",
      description: "Diagnose constraints and latent public assets",
      questionIds: ["GOV_D_12", "GOV_D_13"],
    },
    {
      id: "E",
      title: "Section E: Consolidation and Commitment",
      description: "Test authority transfer willingness to PRASC",
      questionIds: ["GOV_E_14", "GOV_E_15", "GOV_E_16", "GOV_E_17"],
    },
  ],
  questions: {
     GOV_0_01: {
      id: "GOV_0_01",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your name?",
      type: "text",
       required: true
    },
    GOV_0_02: {
      id: "GOV_0_02",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your email address?",
      type: "text", required: true
    },
    GOV_0_03: {
      id: "GOV_0_03",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your phone number?",
      type: "text", required: true
    },
    GOV_0_04: {
      id: "GOV_0_04",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your entity name?",
      type: "text", required: true
    },
    // Section A - Organisation and Mandate
    GOV_A_01: {
      id: "GOV_A_01",
      section: "A",
      sectionTitle: "Organisation and Mandate",
      question: "What is your organisation type?",
      type: "select",
      required: true,
      options: [
        { value: "federal_ministry", label: "Federal Ministry" },
        { value: "federal_regulator", label: "Federal Regulator" },
        { value: "federal_soe_defence", label: "Federal SOE (Defence)" },
        { value: "federal_soe_civilian", label: "Federal SOE (Civilian)" },
        { value: "provincial_ministry", label: "Provincial Ministry" },
        { value: "provincial_regulator", label: "Provincial Regulator" },
        { value: "academic_regulator", label: "Academic Regulator" },
        { value: "financial_regulator", label: "Financial Regulator" },
      ],
    },
    GOV_A_02: {
      id: "GOV_A_02",
      section: "A",
      sectionTitle: "Organisation and Mandate",
      question: "What are your primary relationships to the RAS ecosystem?",
      type: "multi-select",
      required: true,
      options: [
        { value: "policy_formulation", label: "Policy Formulation" },
        { value: "funding_allocation", label: "Funding Allocation" },
        { value: "regulation_certification", label: "Regulation/Certification" },
        { value: "direct_production", label: "Direct Production" },
        { value: "procurement", label: "Procurement" },
        { value: "workforce_development", label: "Workforce Development" },
        { value: "export_promotion", label: "Export Promotion" },
        { value: "standards_setting", label: "Standards Setting" },
        { value: "defence_industrial_coordination", label: "Defence Industrial Coordination" },
      ],
    },
    GOV_A_03: {
      id: "GOV_A_03",
      section: "A",
      sectionTitle: "Organisation and Mandate",
      question: "What is your annual RAS-related budget for the last 3 years? (PKR millions)",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "year_minus_2", label: "2 Years Ago" },
        { key: "year_minus_1", label: "Last Year" },
        { key: "current_year", label: "Current Year" },
      ],
    },

    // Section B - Current RAS Activity
    GOV_B_04: {
      id: "GOV_B_04",
      section: "B",
      sectionTitle: "Current RAS Activity",
      question: "List your RAS programmes/projects/regulations administered (up to 5)",
      type: "multi-row",
      maxRows: 5,
      rowFields: [
        { key: "programme_name", label: "Programme/Project Name", type: "text", placeholder: "Max 280 characters" },
      ],
    },
    GOV_B_05: {
      id: "GOV_B_05",
      section: "B",
      sectionTitle: "Current RAS Activity",
      question: "What is the indigenous content of your top 3 RAS platforms? (Defence-adjacent only)",
      description: "Provide current percentage and 36-month target",
      type: "multi-row",
      maxRows: 3,
      rowFields: [
        { key: "platform_name", label: "Platform Name", type: "text" },
        { key: "current_pct", label: "Current %", type: "number" },
        { key: "target_36m_pct", label: "36-Month Target %", type: "number" },
      ],
    },
    GOV_B_06: {
      id: "GOV_B_06",
      section: "B",
      sectionTitle: "Current RAS Activity",
      question: "Which sub-systems have binding foreign dependency?",
      type: "multi-select",
      required: false,
      options: [
        { value: "engines", label: "Engines" },
        { value: "eo_ir_sensors", label: "EO/IR Sensors" },
        { value: "datalinks", label: "Datalinks" },
        { value: "ics_semiconductors", label: "ICs/Semiconductors" },
        { value: "propellants", label: "Propellants" },
        { value: "software_libraries", label: "Software Libraries" },
        { value: "ai_training_compute", label: "AI Training Compute" },
        { value: "other", label: "Other" },
      ],
    },
    GOV_B_07: {
      id: "GOV_B_07",
      section: "B",
      sectionTitle: "Current RAS Activity",
      question: "What is your current engagement level with Pakistani universities/start-ups?",
      type: "select",
      required: true,
      options: [
        { value: "extensive", label: "Extensive" },
        { value: "moderate", label: "Moderate" },
        { value: "limited", label: "Limited" },
        { value: "none_interested", label: "None - But Interested" },
        { value: "none_no_interest", label: "None - No Interest" },
      ],
    },
    GOV_B_08: {
      id: "GOV_B_08",
      section: "B",
      sectionTitle: "Current RAS Activity",
      question: "List your foreign partner engagements (co-production, ToT, licensing) - up to 5",
      type: "multi-row",
      maxRows: 5,
      rowFields: [
        { key: "partner_country", label: "Partner Country", type: "text" },
        { key: "arrangement_type", label: "Arrangement Type", type: "text", placeholder: "e.g., Co-production, ToT, License" },
        { key: "scope", label: "Scope", type: "text" },
      ],
    },

    // Section C - Regulatory Posture
    GOV_C_09: {
      id: "GOV_C_09",
      section: "C",
      sectionTitle: "Regulatory Posture",
      question: "Rate readiness of regulatory framework (1-5) across 8 areas",
      description: "1 = No framework, 5 = Fully operational framework",
      type: "likert-matrix",
      required: true,
      items: [
        { id: "industrial_robot_safety", label: "Industrial Robot Safety (ISO 10218)" },
        { id: "civil_uas", label: "Civil UAS" },
        { id: "service_robots", label: "Service Robots (ISO 13482)" },
        { id: "autonomous_vehicles", label: "Autonomous Vehicles" },
        { id: "ai_governance", label: "AI Governance" },
        { id: "data_protection", label: "Data Protection" },
        { id: "cybersecurity", label: "Cybersecurity" },
        { id: "export_controls", label: "Export Controls" },
      ],
    },
    GOV_C_10: {
      id: "GOV_C_10",
      section: "C",
      sectionTitle: "Regulatory Posture",
      question: "What specific regulatory gaps are binding on RAS adoption?",
      description: "Name specific clauses, missing legislation (max 280 characters)",
      type: "text",
      maxChars: 280,
      required: true,
    },
    GOV_C_11: {
      id: "GOV_C_11",
      section: "C",
      sectionTitle: "Regulatory Posture",
      question: "What is your timeline to promulgate RAS regulations under current authority?",
      type: "select",
      required: true,
      options: [
        { value: "lt_6m", label: "Less than 6 months" },
        { value: "6_12m", label: "6-12 months" },
        { value: "12_24m", label: "12-24 months" },
        { value: "gt_24m", label: "More than 24 months" },
        { value: "needs_legislation", label: "Needs Legislation" },
      ],
    },

    // Section D - Pivot Questions
    GOV_D_12: {
      id: "GOV_D_12",
      section: "D",
      sectionTitle: "Pivot Questions",
      question: "What are the top 3 constraints preventing execution of your existing RAS mandate?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "mandate_unclear", label: "Mandate Unclear" },
        { value: "budget_inadequate", label: "Budget Inadequate" },
        { value: "legal_authority_missing", label: "Legal Authority Missing" },
        { value: "cross_ministry_friction", label: "Cross-Ministry Friction" },
        { value: "talent_gap", label: "Talent Gap" },
        { value: "data_inaccessible", label: "Data Inaccessible" },
        { value: "procurement_red_tape", label: "Procurement Red Tape" },
        { value: "political_uncertainty", label: "Political Uncertainty" },
        { value: "other", label: "Other" },
      ],
    },
    GOV_D_13: {
      id: "GOV_D_13",
      section: "D",
      sectionTitle: "Pivot Questions",
      question: "What authority/data/infrastructure/asset do you control but are unsure how to deploy?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "underused_dataset", label: "Underused Dataset" },
        { value: "idle_facility", label: "Idle Facility" },
        { value: "regulatory_authority", label: "Regulatory Authority" },
        { value: "land_buildings", label: "Land or Buildings" },
        { value: "trained_workforce", label: "Trained Workforce" },
        { value: "legal_powers", label: "Legal Powers" },
        { value: "relationship_capital", label: "Relationship Capital" },
        { value: "certification_pathway", label: "Certification Pathway" },
        { value: "other", label: "Other" },
      ],
    },

    // Section E - Consolidation and Commitment
    GOV_E_14: {
      id: "GOV_E_14",
      section: "E",
      sectionTitle: "Consolidation and Commitment",
      question: "Rate your willingness (1-5) to transfer/share authority with PRASC across 6 functions",
      description: "1 = Will not transfer, 5 = Ready to transfer immediately",
      type: "likert-matrix",
      required: true,
      items: [
        { id: "policy", label: "Policy" },
        { id: "funding", label: "Funding" },
        { id: "regulation", label: "Regulation" },
        { id: "procurement", label: "Procurement" },
        { id: "workforce", label: "Workforce" },
        { id: "standards", label: "Standards" },
      ],
    },
    GOV_E_15: {
      id: "GOV_E_15",
      section: "E",
      sectionTitle: "Consolidation and Commitment",
      question: "What are your concerns about establishing PRASC?",
      type: "multi-select",
      required: false,
      options: [
        { value: "turf_loss", label: "Turf Loss" },
        { value: "budget_competition", label: "Budget Competition" },
        { value: "reporting_burden", label: "Reporting Burden" },
        { value: "legal_complexity", label: "Legal Complexity" },
        { value: "skills_drain", label: "Skills Drain" },
        { value: "none", label: "None" },
        { value: "other", label: "Other" },
      ],
    },
    GOV_E_16: {
      id: "GOV_E_16",
      section: "E",
      sectionTitle: "Consolidation and Commitment",
      question: "What RAS-specific policy actions will you take in the next 12 months?",
      type: "multi-select",
      required: false,
      options: [
        { value: "regulation_drafting", label: "Regulation Drafting" },
        { value: "fund_release", label: "Fund Release" },
        { value: "procurement_carveout", label: "Procurement Carve-out" },
        { value: "curriculum_reform", label: "Curriculum Reform" },
        { value: "tax_relief", label: "Tax Relief" },
        { value: "skills_programme", label: "Skills Programme" },
        { value: "defence_carveout", label: "Defence Carve-out" },
        { value: "dual_use_export_clarification", label: "Dual-use Export Clarification" },
        { value: "none", label: "None" },
        { value: "other", label: "Other" },
      ],
    },
    GOV_E_17: {
      id: "GOV_E_17",
      section: "E",
      sectionTitle: "Consolidation and Commitment",
      question: "What is the single biggest enabler the PMO could authorise?",
      description: "Max 280 characters",
      type: "text",
      maxChars: 280,
      required: true,
    },
  },
}
