import { Questionnaire, ALL_RAS_CAPABILITIES } from "@/lib/types"

export const industryQuestionnaire: Questionnaire = {
  id: "industry",
  title: "Industry Instrument",
  description: "28 questions for manufacturing firms, exporters, and industrial enterprises",
  sections: [
    {
      id: "A",
      title: "Section A: Firm Profile",
      description: "Establish your organization's classification and baseline metrics",
      questionIds: ["IND_A_01", "IND_A_02", "IND_A_03", "IND_A_04"],
    },
    {
      id: "B",
      title: "Section B: RAS Deployment & Needs",
      description: "Current RAS maturity, assets, and capability needs",
      questionIds: [
        "IND_B_05",
        "IND_B_06",
        "IND_B_07",
        "IND_B_08",
        "IND_B_09",
        "IND_B_10",
        "IND_B_11",
        "IND_B_12",
        "IND_B_13",
        "IND_B_14",
        "IND_B_15",
        "IND_B_16",
        "IND_B_17",
      ],
    },
    {
      id: "C",
      title: "Section C: Pivot Questions",
      description: "Diagnostic core - constraints and latent capabilities",
      questionIds: ["IND_C_18", "IND_C_19"],
    },
    {
      id: "D",
      title: "Section D: Investment Capacity",
      description: "Capex commitment and financing preferences",
      questionIds: ["IND_D_20", "IND_D_21", "IND_D_22"],
    },
    {
      id: "E",
      title: "Section E: Workforce",
      description: "Current talent and future workforce needs",
      questionIds: ["IND_E_23", "IND_E_24", "IND_E_25"],
    },
    {
      id: "F",
      title: "Section F: Economic Outcome & Policy Ask",
      description: "Projected outcomes and policy priorities",
      questionIds: ["IND_F_26", "IND_F_27", "IND_F_28"],
    },
  ],
  questions: {
    // Section A - Firm Profile
    IND_A_01: {
      id: "IND_A_01",
      section: "A",
      sectionTitle: "Firm Profile",
      question: "What is your primary sector?",
      type: "select",
      required: true,
      options: [
        { value: "textiles", label: "Textiles" },
        { value: "automotive_parts", label: "Automotive Parts" },
        { value: "pharma", label: "Pharma" },
        { value: "food_beverage", label: "Food & Beverage" },
        { value: "surgical_instruments", label: "Surgical Instruments" },
        { value: "logistics", label: "Logistics" },
        { value: "agri_processing", label: "Agri-Processing" },
        { value: "cement_steel", label: "Cement & Steel" },
        { value: "chemicals", label: "Chemicals" },
        { value: "electronics", label: "Electronics" },
        { value: "defence_manufacturing", label: "Defence Manufacturing" },
        { value: "other", label: "Other" },
      ],
    },
    IND_A_02: {
      id: "IND_A_02",
      section: "A",
      sectionTitle: "Firm Profile",
      question: "What is your annual revenue band (PKR)?",
      type: "select",
      required: true,
      options: [
        { value: "lt_500m", label: "Less than 500 million" },
        { value: "500m_5bn", label: "500 million - 5 billion" },
        { value: "5bn_20bn", label: "5 - 20 billion" },
        { value: "gt_20bn", label: "More than 20 billion" },
      ],
    },
    IND_A_03: {
      id: "IND_A_03",
      section: "A",
      sectionTitle: "Firm Profile",
      question: "What percentage of your revenue comes from exports?",
      description: "Enter a value between 0 and 100",
      type: "percentage",
      required: true,
    },
    IND_A_04: {
      id: "IND_A_04",
      section: "A",
      sectionTitle: "Firm Profile",
      question: "What is your total employee count and shop-floor employee count?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "total_employees", label: "Total Employees" },
        { key: "shopfloor_employees", label: "Shop-floor Employees" },
      ],
    },

    // Section B - RAS Deployment & Needs
    IND_B_05: {
      id: "IND_B_05",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "What is your current RAS maturity level?",
      type: "select",
      required: true,
      options: [
        { value: "none", label: "None" },
        { value: "evaluating", label: "Evaluating" },
        { value: "piloting", label: "Piloting" },
        { value: "partial_deployment", label: "Partial Deployment" },
        { value: "mature_deployment", label: "Mature Deployment" },
      ],
    },
    IND_B_06: {
      id: "IND_B_06",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "How many of each RAS asset type do you currently have?",
      description: "Enter integer counts for each asset type",
      type: "multi-number",
      required: false,
      numberFields: [
        { key: "industrial_robots", label: "Industrial Robots" },
        { key: "cobots", label: "Cobots" },
        { key: "agv_amr", label: "AGVs/AMRs" },
        { key: "vision_inspection", label: "Vision Inspection Systems" },
        { key: "ai_process_control", label: "AI Process Control" },
        { key: "asrs", label: "AS/RS (Automated Storage)" },
        { key: "drones", label: "Drones" },
        { key: "rpa_bots", label: "RPA Bots" },
      ],
    },
    IND_B_07: {
      id: "IND_B_07",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "When did you first deploy RAS and what is your cumulative capex?",
      type: "multi-number",
      required: false,
      numberFields: [
        { key: "first_deployment_year", label: "First Deployment Year" },
        { key: "cumulative_capex_pkr_m", label: "Cumulative Capex (PKR millions)" },
      ],
    },
    IND_B_08: {
      id: "IND_B_08",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "List your RAS vendors/OEMs and their countries (up to 10)",
      description: "Provide details for each vendor",
      type: "multi-row",
      maxRows: 10,
      rowFields: [
        { key: "asset_type", label: "Asset Type", type: "text", placeholder: "e.g., Industrial Robot" },
        { key: "oem_name", label: "OEM/Vendor Name", type: "text", placeholder: "e.g., FANUC" },
        { key: "country", label: "Country", type: "text", placeholder: "e.g., Japan" },
      ],
    },
    IND_B_09: {
      id: "IND_B_09",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Who built or integrated your RAS systems?",
      type: "select",
      required: false,
      options: [
        { value: "in_house", label: "In-house" },
        { value: "pakistani_integrator", label: "Pakistani Integrator" },
        { value: "pakistani_university", label: "Pakistani University" },
        { value: "pakistani_startup", label: "Pakistani Start-up" },
        { value: "foreign_oem", label: "Foreign OEM" },
        { value: "foreign_integrator", label: "Foreign Integrator" },
        { value: "turnkey", label: "Turnkey Solution" },
      ],
    },
    IND_B_10: {
      id: "IND_B_10",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Rate your current maturity (1-5) across 24 RAS capabilities",
      description: "1 = No capability, 5 = World-class capability",
      type: "likert-matrix",
      required: true,
      items: ALL_RAS_CAPABILITIES,
    },
    IND_B_11: {
      id: "IND_B_11",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "What are your top 3 planned RAS applications for the next 24 months?",
      type: "rank",
      rankCount: 3,
      required: true,
      options: [
        ...ALL_RAS_CAPABILITIES.map((cap) => ({ value: cap.id, label: cap.label })),
        { value: "other", label: "Other" },
      ],
    },
    IND_B_12: {
      id: "IND_B_12",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Which capabilities do you need but cannot source from Pakistan?",
      description: "Select all that apply",
      type: "multi-select",
      required: false,
      options: ALL_RAS_CAPABILITIES.map((cap) => ({ value: cap.id, label: cap.label })),
    },
    IND_B_13: {
      id: "IND_B_13",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Describe your most important capability need",
      description: "Maximum 280 characters",
      type: "composite",
      required: true,
      confidenceLikert: true,
      compositeFields: [
        { key: "description", label: "Description", type: "text", required: true },
      ],
      maxChars: 280,
    },
    IND_B_14: {
      id: "IND_B_14",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "How would you describe your production data quality?",
      type: "select",
      required: true,
      options: [
        { value: "labelled_historical", label: "Labelled Historical Data" },
        { value: "unlabelled_historical", label: "Unlabelled Historical Data" },
        { value: "realtime_only", label: "Real-time Only" },
        { value: "partial", label: "Partial Collection" },
        { value: "no_systematic", label: "No Systematic Collection" },
      ],
    },
    IND_B_15: {
      id: "IND_B_15",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Have you engaged with Pakistani academia or start-ups for RAS?",
      type: "select",
      required: true,
      options: [
        { value: "yes_successful", label: "Yes - Successful" },
        { value: "yes_partial", label: "Yes - Partial Success" },
        { value: "yes_abandoned", label: "Yes - Abandoned" },
        { value: "no_unaware", label: "No - Unaware of Options" },
        { value: "no_confidence", label: "No - Lack of Confidence" },
        { value: "no_other", label: "No - Other Reasons" },
      ],
    },
    IND_B_16: {
      id: "IND_B_16",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "Provide details of your foreign RAS sourcing (up to 5)",
      type: "multi-row",
      maxRows: 5,
      rowFields: [
        { key: "country", label: "Country", type: "text", placeholder: "e.g., Germany" },
        { key: "supplier", label: "Supplier", type: "text", placeholder: "e.g., Siemens" },
        { key: "annual_spend_usd", label: "Annual Spend (USD)", type: "number" },
      ],
    },
    IND_B_17: {
      id: "IND_B_17",
      section: "B",
      sectionTitle: "RAS Deployment & Needs",
      question: "What conditions would make you commission a Pakistani partner instead?",
      type: "multi-select",
      required: false,
      options: [
        { value: "price_match", label: "Price Match" },
        { value: "timeline_guarantee", label: "Timeline Guarantee" },
        { value: "ip_clarity", label: "IP Clarity" },
        { value: "track_record", label: "Proven Track Record" },
        { value: "dedicated_team", label: "Dedicated Team" },
        { value: "matched_funding", label: "Matched Funding" },
        { value: "performance_bond", label: "Performance Bond" },
        { value: "post_deployment_support", label: "Post-deployment Support" },
      ],
    },

    // Section C - Pivot Questions
    IND_C_18: {
      id: "IND_C_18",
      section: "C",
      sectionTitle: "Pivot Questions",
      question: "What are the top 3 constraints preventing your RAS deployment?",
      description: "Rank your top 3 blockers",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "capital_cost", label: "Capital Cost" },
        { value: "payback_long", label: "Payback Too Long" },
        { value: "no_local_integrator", label: "No Local Integrator" },
        { value: "skilled_workforce_gap", label: "Skilled Workforce Gap" },
        { value: "regulatory_uncertainty", label: "Regulatory Uncertainty" },
        { value: "quality_concerns", label: "Quality Concerns" },
        { value: "aftermarket_risk", label: "Aftermarket Risk" },
        { value: "customer_acceptance", label: "Customer Acceptance" },
        { value: "supply_chain", label: "Supply Chain" },
        { value: "cybersecurity_risk", label: "Cybersecurity Risk" },
        { value: "data_quality", label: "Data Quality" },
        { value: "ip_protection", label: "IP Protection" },
        { value: "forex_volatility", label: "Forex Volatility" },
        { value: "other", label: "Other" },
      ],
    },
    IND_C_19: {
      id: "IND_C_19",
      section: "C",
      sectionTitle: "Pivot Questions",
      question: "What knowledge/skill/tech do you have but are unsure how to commercialise?",
      description: "Rank your top 3 latent capabilities",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      prascOptIn: true,
      options: [
        { value: "excess_engineering", label: "Excess Engineering Capacity" },
        { value: "unused_data", label: "Unused Industrial Data" },
        { value: "niche_knowhow", label: "Niche Process Know-how" },
        { value: "idle_test_facilities", label: "Idle Test Facilities" },
        { value: "domain_expert_team", label: "Domain Expert Team" },
        { value: "customer_relationships", label: "Customer Relationships" },
        { value: "manufacturing_capacity", label: "Manufacturing Capacity" },
        { value: "software_capability", label: "Software Capability" },
        { value: "physical_infrastructure", label: "Physical Infrastructure" },
        { value: "licenses_certifications", label: "Licenses/Certifications" },
        { value: "partner_network", label: "Partner Network" },
        { value: "other", label: "Other" },
      ],
    },

    // Section D - Investment Capacity
    IND_D_20: {
      id: "IND_D_20",
      section: "D",
      sectionTitle: "Investment Capacity",
      question: "What is your 36-month capex commitment under these scenarios? (PKR millions)",
      description: "Provide estimates for each scenario",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "scenario_a", label: "Scenario A: Status Quo" },
        { key: "scenario_b", label: "Scenario B: PRASC OEM Pricing -20% + Training" },
        { key: "scenario_c", label: "Scenario C: B + 25% Matching Grant" },
      ],
    },
    IND_D_21: {
      id: "IND_D_21",
      section: "D",
      sectionTitle: "Investment Capacity",
      question: "What is your acceptable payback horizon for RAS investments?",
      type: "select",
      required: true,
      options: [
        { value: "lt_12m", label: "Less than 12 months" },
        { value: "13_18m", label: "13-18 months" },
        { value: "19_24m", label: "19-24 months" },
        { value: "25_36m", label: "25-36 months" },
        { value: "gt_36m", label: "More than 36 months" },
      ],
    },
    IND_D_22: {
      id: "IND_D_22",
      section: "D",
      sectionTitle: "Investment Capacity",
      question: "Rank your top 2 preferred financing instruments",
      type: "rank",
      rankCount: 2,
      required: true,
      options: [
        { value: "internal_cash", label: "Internal Cash" },
        { value: "term_loan", label: "Term Loan" },
        { value: "sbp_refinance", label: "SBP Refinance" },
        { value: "islamic_ijarah", label: "Islamic Ijarah" },
        { value: "islamic_musharakah", label: "Islamic Diminishing Musharakah" },
        { value: "vendor_financing", label: "Vendor Financing" },
        { value: "matched_grant", label: "Matched Grant" },
        { value: "equity", label: "Equity" },
      ],
    },

    // Section E - Workforce
    IND_E_23: {
      id: "IND_E_23",
      section: "E",
      sectionTitle: "Workforce",
      question: "How many engineers/technicians with formal RAS training do you have today?",
      type: "number",
      required: true,
    },
    IND_E_24: {
      id: "IND_E_24",
      section: "E",
      sectionTitle: "Workforce",
      question: "How many RAS-certified hires can you absorb per year over 3 years?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "year_1", label: "Year 1" },
        { key: "year_2", label: "Year 2" },
        { key: "year_3", label: "Year 3" },
      ],
    },
    IND_E_25: {
      id: "IND_E_25",
      section: "E",
      sectionTitle: "Workforce",
      question: "How many apprenticeship slots can you offer and at what cost per slot?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "slots_per_year", label: "Slots per Year" },
        { key: "cost_per_slot_pkr", label: "Cost per Slot (PKR)" },
      ],
    },

    // Section F - Economic Outcome & Policy Ask
    IND_F_26: {
      id: "IND_F_26",
      section: "F",
      sectionTitle: "Economic Outcome & Policy Ask",
      question: "What are your projected 36-month outcomes after RAS investment?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "export_growth_pct", label: "Export Growth (%)" },
        { key: "productivity_uplift_pct", label: "Productivity Uplift (%)" },
        { key: "scrap_reduction_pct", label: "Scrap Reduction (%)" },
        { key: "headcount_change_pct", label: "Headcount Change (%)" },
        { key: "new_product_lines", label: "New Product Lines (count)" },
      ],
    },
    IND_F_27: {
      id: "IND_F_27",
      section: "F",
      sectionTitle: "Economic Outcome & Policy Ask",
      question: "What are the top 3 government policy changes that would accelerate your investment?",
      type: "rank",
      rankCount: 3,
      required: true,
      options: [
        { value: "duty_zero", label: "Zero Duty on RAS Equipment" },
        { value: "accelerated_depreciation", label: "Accelerated Depreciation" },
        { value: "rd_tax_credit", label: "R&D Tax Credit" },
        { value: "sbp_refinance", label: "SBP Refinance Line" },
        { value: "fbr_simplification", label: "FBR Process Simplification" },
        { value: "edb_carveout", label: "EDB Carve-out" },
        { value: "psqca_certification", label: "PSQCA Fast-track Certification" },
        { value: "sez_subsidies", label: "SEZ Subsidies" },
        { value: "visa_fast_track", label: "Visa Fast-track for Experts" },
        { value: "mod_offset", label: "MoD Offset Programme" },
        { value: "defence_procurement_carveout", label: "Defence Procurement Carve-out" },
      ],
    },
    IND_F_28: {
      id: "IND_F_28",
      section: "F",
      sectionTitle: "Economic Outcome & Policy Ask",
      question:
        "How willing are you to co-sign an Industrial Adoption Charter with binding 5-year KPIs?",
      description: "1 = Strongly reject, 5 = Ready to sign within 90 days",
      type: "likert",
      required: true,
    },
  },
}
