import { Questionnaire } from "@/lib/types"

export const investorsQuestionnaire: Questionnaire = {
  id: "investors",
  title: "Investors Instrument",
  description: "16 questions for banks, VCs, family offices, DFIs, and capital providers",
  sections: [
      {
      id: "0",
      title: "Section 0: Personal Information",
      description: "  Collect respondent's contact details for follow-up and validation purposes",
      questionIds: ["INV_0_01", "INV_0_02", "INV_0_03", "INV_0_04"],
    },
    {
      id: "A",
      title: "Section A: Investor Profile",
      description: "Profile by class, mandate, size, and current RAS exposure",
      questionIds: ["INV_A_01", "INV_A_02", "INV_A_03", "INV_A_04"],
    },
    {
      id: "B",
      title: "Section B: Appetite and Conditions",
      description: "Capture appetite under different scenarios",
      questionIds: ["INV_B_05", "INV_B_06", "INV_B_07", "INV_B_08", "INV_B_09"],
    },
    {
      id: "C",
      title: "Section C: Blockers, Pivot, Exit",
      description: "Structural blockers and exit pathways",
      questionIds: ["INV_C_10", "INV_C_11", "INV_C_12", "INV_C_13", "INV_C_14"],
    },
    {
      id: "D",
      title: "Section D: Commitment and Policy Ask",
      description: "Willingness to publicly commit alongside PRASC launch",
      questionIds: ["INV_D_15", "INV_D_16"],
    },
  ],
  questions: {
    // Section 0 - Personal Information
    INV_0_01: {
      id: "INV_0_01",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your name?",
      type: "text",
       required: true
    },
    INV_0_02: {
      id: "INV_0_02",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your email address?",
      type: "text", required: true
    },
    INV_0_03: {
      id: "INV_0_03",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your phone number?",
      type: "text", required: true
    },
    INV_0_04: {
      id: "INV_0_04",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your entity name?",
      type: "text", required: true
    },
    // Section A - Investor Profile
    INV_A_01: {
      id: "INV_A_01",
      section: "A",
      sectionTitle: "Investor Profile",
      question: "What is your investor class?",
      type: "select",
      required: true,
      options: [
        { value: "commercial_bank", label: "Commercial Bank" },
        { value: "islamic_bank", label: "Islamic Bank" },
        { value: "sbp", label: "SBP" },
        { value: "dfi", label: "DFI (Development Finance Institution)" },
        { value: "local_vc", label: "Local VC" },
        { value: "local_pe", label: "Local PE" },
        { value: "family_office", label: "Family Office" },
        { value: "corporate_vc", label: "Corporate VC" },
        { value: "foreign_vc", label: "Foreign VC" },
        { value: "foreign_pe", label: "Foreign PE" },
        { value: "sovereign_fund", label: "Sovereign Fund" },
        { value: "psx_corporate", label: "PSX Corporate" },
      ],
    },
    INV_A_02: {
      id: "INV_A_02",
      section: "A",
      sectionTitle: "Investor Profile",
      question: "What is your geographic mandate?",
      type: "select",
      required: true,
      options: [
        { value: "pakistan_only", label: "Pakistan Only" },
        { value: "pakistan_regional", label: "Pakistan + Regional" },
        { value: "global_incl_pakistan", label: "Global Including Pakistan" },
        { value: "regional_only", label: "Regional Only" },
      ],
    },
    INV_A_03: {
      id: "INV_A_03",
      section: "A",
      sectionTitle: "Investor Profile",
      question: "What is your current AUM/lending book and tech/industrial allocation?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "aum_usd_m", label: "Total AUM/Lending Book (USD millions)" },
        { key: "tech_industrial_pct", label: "Tech/Industrial Share (%)" },
      ],
    },
    INV_A_04: {
      id: "INV_A_04",
      section: "A",
      sectionTitle: "Investor Profile",
      question: "What is your current exposure to RAS-related investments? (USD millions)",
      type: "number",
      required: true,
    },

    // Section B - Appetite and Conditions
    INV_B_05: {
      id: "INV_B_05",
      section: "B",
      sectionTitle: "Appetite and Conditions",
      question: "Rank the top 3 decisive factors in your 'yes' decision",
      type: "rank",
      rankCount: 3,
      required: true,
      options: [
        { value: "track_record_team", label: "Track Record Team" },
        { value: "proven_customers", label: "Proven Customers" },
        { value: "ip_clear", label: "IP Clear" },
        { value: "foreign_lead_investor", label: "Foreign Lead Investor" },
        { value: "government_anchor_customer", label: "Government Anchor Customer" },
        { value: "collateral_coverage", label: "Collateral Coverage" },
        { value: "proven_exit", label: "Proven Exit" },
        { value: "foreign_revenue_share", label: "Foreign Revenue Share" },
        { value: "grant_co_funding", label: "Grant Co-funding" },
        { value: "regulatory_clarity", label: "Regulatory Clarity" },
      ],
    },
    INV_B_06: {
      id: "INV_B_06",
      section: "B",
      sectionTitle: "Appetite and Conditions",
      question: "What is your typical ticket-size range? (USD thousands)",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "min", label: "Minimum" },
        { key: "typical", label: "Typical" },
        { key: "max", label: "Maximum" },
      ],
    },
    INV_B_07: {
      id: "INV_B_07",
      section: "B",
      sectionTitle: "Appetite and Conditions",
      question: "What is your 36-month underwriting willingness under 3 scenarios? (USD millions)",
      description: "This is the key question - delta from A to C measures capital PRASC unlocks",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "scenario_a", label: "Scenario A: Status Quo" },
        { key: "scenario_b", label: "Scenario B: PRASC Sovereign RAS Fund + 25% Match" },
        { key: "scenario_c", label: "Scenario C: B + Pilot Customer Programme" },
      ],
    },
    INV_B_08: {
      id: "INV_B_08",
      section: "B",
      sectionTitle: "Appetite and Conditions",
      question: "What is your preferred deal stage?",
      type: "select",
      required: true,
      options: [
        { value: "pre_seed", label: "Pre-seed" },
        { value: "seed", label: "Seed" },
        { value: "series_a", label: "Series A" },
        { value: "growth", label: "Growth" },
        { value: "buyout", label: "Buyout" },
        { value: "working_capital", label: "Working Capital" },
        { value: "project_finance", label: "Project Finance" },
        { value: "trade_finance", label: "Trade Finance" },
      ],
    },
    INV_B_09: {
      id: "INV_B_09",
      section: "B",
      sectionTitle: "Appetite and Conditions",
      question: "Would a dedicated SBP refinancing line at KIBOR-3, 10y tenor materially change your willingness?",
      description: "Banks/DFIs only. 1 = No change, 5 = Major change",
      type: "likert",
      required: false,
    },

    // Section C - Blockers, Pivot, Exit
    INV_C_10: {
      id: "INV_C_10",
      section: "C",
      sectionTitle: "Blockers, Pivot, Exit",
      question: "Rank the top 3 structural blockers to RAS capital in Pakistan",
      type: "rank",
      rankCount: 3,
      required: true,
      options: [
        { value: "exit_weakness", label: "Exit Weakness" },
        { value: "rupee_depreciation", label: "Rupee Depreciation" },
        { value: "tax_uncertainty", label: "Tax Uncertainty" },
        { value: "founder_thinness", label: "Founder Thinness" },
        { value: "legal_enforceability", label: "Legal Enforceability" },
        { value: "regulatory_unpredictability", label: "Regulatory Unpredictability" },
        { value: "co_funder_thin", label: "Co-funder Thin" },
        { value: "profit_repatriation", label: "Profit Repatriation" },
        { value: "ip_weak", label: "IP Weak" },
      ],
    },
    INV_C_11: {
      id: "INV_C_11",
      section: "C",
      sectionTitle: "Blockers, Pivot, Exit",
      question: "Which global OEMs would you finance if they established a Pakistan entity?",
      type: "multi-select",
      required: false,
      options: [
        { value: "abb", label: "ABB" },
        { value: "fanuc", label: "FANUC" },
        { value: "kuka", label: "KUKA" },
        { value: "universal_robots", label: "Universal Robots" },
        { value: "siemens", label: "Siemens" },
        { value: "nvidia", label: "NVIDIA" },
        { value: "unitree", label: "Unitree" },
        { value: "agibot", label: "Agibot" },
        { value: "festo", label: "Festo" },
        { value: "mitsubishi", label: "Mitsubishi" },
        { value: "rockwell", label: "Rockwell" },
        { value: "baykar", label: "Baykar" },
        { value: "aselsan", label: "Aselsan" },
        { value: "iai", label: "IAI" },
        { value: "thales", label: "Thales" },
        { value: "hanwha", label: "Hanwha" },
        { value: "other", label: "Other" },
      ],
    },
    INV_C_12: {
      id: "INV_C_12",
      section: "C",
      sectionTitle: "Blockers, Pivot, Exit",
      question: "What are realistic exit pathways for a Pakistani RAS portfolio company?",
      type: "multi-select",
      required: true,
      options: [
        { value: "psx_listing", label: "PSX Listing" },
        { value: "foreign_listing", label: "Foreign Listing" },
        { value: "trade_sale_foreign", label: "Trade Sale (Foreign)" },
        { value: "trade_sale_domestic", label: "Trade Sale (Domestic)" },
        { value: "secondary_vc", label: "Secondary VC" },
        { value: "government_buyback", label: "Government Buyback" },
        { value: "none_realistic", label: "None Realistic" },
      ],
    },
    INV_C_13: {
      id: "INV_C_13",
      section: "C",
      sectionTitle: "Blockers, Pivot, Exit",
      question: "What are the top 3 constraints preventing more capital deployment?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "deal_pipeline", label: "Deal Pipeline" },
        { value: "risk_pricing", label: "Risk Pricing" },
        { value: "regulatory_clarity", label: "Regulatory Clarity" },
        { value: "exit_path", label: "Exit Path" },
        { value: "co_funding", label: "Co-funding" },
        { value: "fx_risk", label: "FX Risk" },
        { value: "talent_validation", label: "Talent Validation" },
        { value: "due_diligence_cost", label: "Due Diligence Cost" },
        { value: "other", label: "Other" },
      ],
    },
    INV_C_14: {
      id: "INV_C_14",
      section: "C",
      sectionTitle: "Blockers, Pivot, Exit",
      question: "What capital/network/expertise could you deploy but lack structure or partner?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "sector_expertise", label: "Sector Expertise" },
        { value: "deal_network", label: "Deal Network" },
        { value: "regional_capital", label: "Regional Capital" },
        { value: "exit_partners", label: "Exit Partners" },
        { value: "underwriting_capacity", label: "Underwriting Capacity" },
        { value: "regulatory_relationships", label: "Regulatory Relationships" },
        { value: "grant_co_funding", label: "Grant Co-funding" },
        { value: "other", label: "Other" },
      ],
    },

    // Section D - Commitment and Policy Ask
    INV_D_15: {
      id: "INV_D_15",
      section: "D",
      sectionTitle: "Commitment and Policy Ask",
      question: "What indicative commitment would you publicly announce alongside PRASC launch?",
      type: "composite",
      required: true,
      compositeFields: [
        { key: "amount_usd_m", label: "Amount (USD millions)", type: "number", required: true },
        {
          key: "confidence",
          label: "Confidence Level",
          type: "select",
          required: true,
          options: [
            { value: "exploratory", label: "Exploratory" },
            { value: "conditional", label: "Conditional" },
            { value: "firm_subject_dd", label: "Firm Subject to DD" },
            { value: "board_approved", label: "Board Approved" },
          ],
        },
      ],
    },
    INV_D_16: {
      id: "INV_D_16",
      section: "D",
      sectionTitle: "Commitment and Policy Ask",
      question: "What single irreversible Government action in the next 90 days would unlock capital at scale?",
      description: "Max 280 characters",
      type: "text",
      maxChars: 280,
      required: true,
    },
  },
}
