import { Questionnaire } from "@/lib/types";

export const startupsQuestionnaire: Questionnaire = {
  id: "startups",
  title: "Start-ups Instrument",
  description: "19 questions for robotics and automation start-ups",
  sections: [
    {
      id: "0",
      title: "Section 0: Personal Information",
      description:
        "  Collect respondent's contact details for follow-up and validation purposes",
      questionIds: ["STR_0_01", "STR_0_02", "STR_0_03", "STR_0_04"],
    },
    {
      id: "A",
      title: "Section A: Company Profile",
      description: "Company profile, team, capital, and revenue",
      questionIds: ["STR_A_01", "STR_A_02", "STR_A_03", "STR_A_04", "STR_A_05"],
    },
    {
      id: "B",
      title: "Section B: Technology, Product, Customers",
      description: "Product, technology, customers, and IP position",
      questionIds: [
        "STR_B_06",
        "STR_B_07",
        "STR_B_08",
        "STR_B_09",
        "STR_B_10",
        "STR_B_11",
      ],
    },
    {
      id: "C",
      title: "Section C: Ecosystem and Pivot Questions",
      description: "Ecosystem ties and diagnostic questions",
      questionIds: ["STR_C_12", "STR_C_13", "STR_C_14", "STR_C_15"],
    },
    {
      id: "D",
      title: "Section D: Investment Readiness",
      description: "Investment readiness and policy asks",
      questionIds: ["STR_D_16", "STR_D_17", "STR_D_18", "STR_D_19"],
    },
  ],
  questions: {
    // Section 0 - Personal Information
    STR_0_01: {
      id: "STR_0_01",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your name?",
      type: "text",
      required: true,
    },
    STR_0_02: {
      id: "STR_0_02",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your email address?",
      type: "text",
      required: true,
    },
    STR_0_03: {
      id: "STR_0_03",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your phone number?",
      type: "text",
      required: true,
    },
    STR_0_04: {
      id: "STR_0_04",
      section: "0",
      sectionTitle: "Personal Information",
      question: "What is your entity name?",
      type: "text",
      required: true,
    },
    // Section A - Company Profile
    STR_A_01: {
      id: "STR_A_01",
      section: "A",
      sectionTitle: "Company Profile",
      question: "When was your company founded and what is your current stage?",
      type: "composite",
      required: true,
      compositeFields: [
        {
          key: "year_founded",
          label: "Year Founded",
          type: "number",
          required: true,
        },
        {
          key: "stage",
          label: "Current Stage",
          type: "select",
          required: true,
          options: [
            { value: "idea", label: "Idea" },
            { value: "prototype", label: "Prototype" },
            { value: "pilot", label: "Pilot" },
            { value: "early_revenue", label: "Early Revenue" },
            { value: "growth", label: "Growth" },
            { value: "profitable", label: "Profitable" },
            { value: "exited", label: "Exited" },
          ],
        },
      ],
    },
    STR_A_02: {
      id: "STR_A_02",
      section: "A",
      sectionTitle: "Company Profile",
      question: "What is your team composition?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "total_team", label: "Total Team Size" },
        { key: "technical_team", label: "Technical Team" },
        { key: "rd_phds", label: "R&D PhDs" },
      ],
    },
    STR_A_03: {
      id: "STR_A_03",
      section: "A",
      sectionTitle: "Company Profile",
      question: "What is your primary RAS domain?",
      type: "select",
      required: true,
      options: [
        { value: "industrial_automation", label: "Industrial Automation" },
        { value: "agri_robotics", label: "Agri-robotics" },
        { value: "medical_assistive", label: "Medical/Assistive" },
        { value: "drone_services", label: "Drone Services" },
        { value: "defence_dual_use", label: "Defence Dual-use" },
        { value: "logistics_robotics", label: "Logistics Robotics" },
        { value: "ai_software_only", label: "AI Software Only" },
        { value: "other", label: "Other" },
      ],
    },
    STR_A_04: {
      id: "STR_A_04",
      section: "A",
      sectionTitle: "Company Profile",
      question: "What is your total capital raised and source mix?",
      description: "Percentages should sum to 100%",
      type: "composite",
      required: true,
      compositeFields: [
        {
          key: "total_usd_k",
          label: "Total Capital (USD thousands)",
          type: "number",
          required: true,
        },
        { key: "founder_pct", label: "Founder (%)", type: "number" },
        { key: "angel_pct", label: "Angel (%)", type: "number" },
        { key: "vc_pct", label: "VC (%)", type: "number" },
        { key: "grant_pct", label: "Grant (%)", type: "number" },
        {
          key: "corporate_revenue_pct",
          label: "Corporate Revenue (%)",
          type: "number",
        },
        { key: "other_pct", label: "Other (%)", type: "number" },
      ],
    },
    STR_A_05: {
      id: "STR_A_05",
      section: "A",
      sectionTitle: "Company Profile",
      question: "What is your current revenue band (annualised, USD)?",
      type: "select",
      required: true,
      options: [
        { value: "pre_revenue", label: "Pre-revenue" },
        { value: "lt_50k", label: "Less than $50k" },
        { value: "50k_250k", label: "$50k - $250k" },
        { value: "250k_1m", label: "$250k - $1m" },
        { value: "1m_5m", label: "$1m - $5m" },
        { value: "gt_5m", label: "More than $5m" },
      ],
    },

    // Section B - Technology, Product, Customers
    STR_B_06: {
      id: "STR_B_06",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question: "Describe your core product and technical differentiator",
      description: "Max 280 characters (40 words guidance)",
      type: "text",
      maxChars: 280,
      required: true,
    },
    STR_B_07: {
      id: "STR_B_07",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question: "What is the current TRL of your lead product?",
      type: "select",
      required: true,
      options: [
        { value: "1", label: "TRL 1 - Basic Principles" },
        { value: "2", label: "TRL 2 - Technology Concept" },
        { value: "3", label: "TRL 3 - Proof of Concept" },
        { value: "4", label: "TRL 4 - Lab Validation" },
        { value: "5", label: "TRL 5 - Relevant Environment" },
        { value: "6", label: "TRL 6 - Demonstrated" },
        { value: "7", label: "TRL 7 - Operational" },
        { value: "8", label: "TRL 8 - Qualified" },
        { value: "9", label: "TRL 9 - Mission Proven" },
      ],
    },
    STR_B_08: {
      id: "STR_B_08",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question: "Provide customer details",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "customer_count", label: "Total Customer Count" },
        { key: "largest_contract_usd", label: "Largest Contract Value (USD)" },
      ],
    },
    STR_B_09: {
      id: "STR_B_09",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question: "What is your export customer presence?",
      type: "select",
      required: true,
      options: [
        { value: "no_exports", label: "No Exports" },
        { value: "pilot_abroad", label: "Pilot Abroad" },
        { value: "active_1_country", label: "Active in 1 Country" },
        {
          value: "active_multi_country",
          label: "Active in Multiple Countries",
        },
      ],
    },
    STR_B_10: {
      id: "STR_B_10",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question: "What is your IP position?",
      type: "composite",
      required: true,
      compositeFields: [
        {
          key: "ip_status",
          label: "IP Status",
          type: "multi-select",
          options: [
            { value: "patents_filed", label: "Patents Filed" },
            { value: "patents_granted", label: "Patents Granted" },
            { value: "trade_secrets", label: "Trade Secrets" },
            { value: "none", label: "None" },
          ],
        },
        {
          key: "ownership",
          label: "Ownership",
          type: "select",
          options: [
            { value: "founder", label: "Founder" },
            { value: "company", label: "Company" },
            { value: "university", label: "University" },
            { value: "shared", label: "Shared" },
            { value: "disputed", label: "Disputed" },
            { value: "none", label: "None" },
          ],
        },
      ],
    },
    STR_B_11: {
      id: "STR_B_11",
      section: "B",
      sectionTitle: "Technology, Product, Customers",
      question:
        "What resources do you need to reach full commercial readiness?",
      type: "multi-number",
      required: true,
      numberFields: [
        { key: "usd_k", label: "Capital Needed (USD thousands)" },
        { key: "months", label: "Months to Readiness" },
      ],
    },

    // Section C - Ecosystem and Pivot Questions
    STR_C_12: {
      id: "STR_C_12",
      section: "C",
      sectionTitle: "Ecosystem & Pivot Questions",
      question:
        "What is your engagement with Pakistani academia (last 24 months)?",
      type: "select",
      required: true,
      options: [
        { value: "co_development", label: "Co-development" },
        { value: "research_contract", label: "Research Contract" },
        { value: "talent_pipeline_only", label: "Talent Pipeline Only" },
        { value: "none_tried", label: "None - Tried" },
        { value: "none_no_interest", label: "None - No Interest" },
      ],
    },
    STR_C_13: {
      id: "STR_C_13",
      section: "C",
      sectionTitle: "Ecosystem & Pivot Questions",
      question:
        "What is your engagement with Pakistani industry as customer/partner?",
      type: "select",
      required: true,
      options: [
        { value: "primary_customer_base", label: "Primary Customer Base" },
        { value: "occasional", label: "Occasional" },
        { value: "only_international", label: "Only International" },
        { value: "piloting", label: "Piloting" },
        { value: "none", label: "None" },
      ],
    },
    STR_C_14: {
      id: "STR_C_14",
      section: "C",
      sectionTitle: "Ecosystem & Pivot Questions",
      question: "What are the top 3 constraints preventing you from scaling?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      options: [
        { value: "no_local_buyers", label: "No Local Buyers" },
        { value: "no_growth_capital", label: "No Growth Capital" },
        { value: "talent_thinness", label: "Talent Thinness" },
        { value: "ip_protection", label: "IP Protection" },
        { value: "regulatory_unclarity", label: "Regulatory Unclarity" },
        { value: "export_red_tape", label: "Export Red Tape" },
        { value: "infra_costs", label: "Infrastructure Costs" },
        { value: "founder_bandwidth", label: "Founder Bandwidth" },
        { value: "cofounder_split", label: "Co-founder Split" },
        { value: "other", label: "Other" },
      ],
    },
    STR_C_15: {
      id: "STR_C_15",
      section: "C",
      sectionTitle: "Ecosystem & Pivot Questions",
      question:
        "What tech/skill/asset do you have but cannot reach customers/capital/partners?",
      type: "rank",
      rankCount: 3,
      required: true,
      confidenceLikert: true,
      prascOptIn: true,
      options: [
        { value: "unique_dataset", label: "Unique Dataset" },
        { value: "core_algorithm", label: "Core Algorithm" },
        { value: "hardware_design", label: "Hardware Design" },
        { value: "domain_relationships", label: "Domain Relationships" },
        { value: "certified_team", label: "Certified Team" },
        { value: "low_cost_manufacturing", label: "Low-cost Manufacturing" },
        { value: "export_partner", label: "Export Partner" },
        { value: "niche_market_access", label: "Niche Market Access" },
        { value: "other", label: "Other" },
      ],
    },

    // Section D - Investment Readiness
    STR_D_16: {
      id: "STR_D_16",
      section: "D",
      sectionTitle: "Investment Readiness",
      question:
        "How much capital can you absorb productively in 24 months and from what source?",
      type: "composite",
      required: true,
      compositeFields: [
        {
          key: "capital_usd_k",
          label: "Capital Absorbable (USD thousands)",
          type: "number",
          required: true,
        },
        {
          key: "preferred_sources",
          label: "Preferred Sources (Rank 2)",
          type: "rank",
          options: [
            { value: "angel", label: "Angel" },
            { value: "local_vc", label: "Local VC" },
            { value: "foreign_vc", label: "Foreign VC" },
            { value: "government_grant", label: "Government Grant" },
            { value: "corporate_partner", label: "Corporate Partner" },
            { value: "debt", label: "Debt" },
            { value: "crowdfunding", label: "Crowdfunding" },
            { value: "family_office", label: "Family Office" },
          ],
        },
      ],
    },
    STR_D_17: {
      id: "STR_D_17",
      section: "D",
      sectionTitle: "Investment Readiness",
      question:
        "How willing are you to relocate abroad if Pakistani environment does not improve?",
      description: "1 = Will never leave, 5 = Actively planning to relocate",
      type: "likert",
      required: true,
    },
    STR_D_18: {
      id: "STR_D_18",
      section: "D",
      sectionTitle: "Investment Readiness",
      question:
        "Rank the top 3 PRASC interventions that would most accelerate your growth",
      type: "rank",
      rankCount: 3,
      required: true,
      options: [
        { value: "sovereign_fund", label: "Sovereign Fund" },
        { value: "pilot_customer", label: "Pilot Customer" },
        { value: "ip_protection", label: "IP Protection" },
        { value: "talent_visa", label: "Talent Visa" },
        { value: "export_certification", label: "Export Certification" },
        { value: "incubator_facility", label: "Incubator Facility" },
        { value: "regulatory_sandbox", label: "Regulatory Sandbox" },
        {
          value: "public_procurement_carveout",
          label: "Public Procurement Carve-out",
        },
      ],
    },
    STR_D_19: {
      id: "STR_D_19",
      section: "D",
      sectionTitle: "Investment Readiness",
      question:
        "What single decisive Government action in the next 90 days would help you most?",
      description: "Max 280 characters",
      type: "text",
      maxChars: 280,
      required: true,
    },
  },
};
